### PR TITLE
Feature/npm badge

### PR DESCRIPTION
**Pull request by BasileTrujillo**
Look like : 

[NPM](https://www.npmjs.com/package/eslint-config-exaprint)

### CODE REVIEW

**Comment by kevinrambaud** [comment]
Ahaha nice 😎
What about using small badges ? Like there https://shields.io ? For example, we could have badges for : npm version (current), npm download

**Comment by BasileTrujillo** [comment]
Why not but how do you keep informations up to date with these badges?

**Comment by kevinrambaud** [comment]
The shields service does it automatically. See example https://img.shields.io/npm/dt/eslint-config-exaprint.svg for the npm download badge

**Comment by BasileTrujillo** [comment]
NIce !
 you gotta show me how did you do that :)

**Pull request merged**
